language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - nightly
matrix:
  include:
    - rust: stable
      env: FLAGS="--no-default-features"
    - rust: nightly
      env: FLAGS="-Z minimal-versions"
    - rust: nightly
      env:
        - FUZZIT_TARGET="png-decoder"
        - FUZZIT_BINARY="decode"
      services:
        - docker
  allow_failures:
    - rust: nightly
      env: FLAGS="-Z minimal-versions"

script:
  - cargo build -v $FLAGS
  - cargo doc -v $FLAGS
  - cargo test -v $FLAGS
  - [[ -n "$FUZZIT_TARGET" ]] && ./fuzzit.sh "$FUZZIT_TARGET" "$FUZZIT_BINARY"
