[package]
name = "png"
version = "0.13.0"
license = "MIT/Apache-2.0"
description = "PNG decoding and encoding library in pure Rust"
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/PistonDevelopers/image-png.git"
exclude = [
    "tests/*",
]

[dependencies]
inflate = "0.4.3"
deflate = { version = "0.7.19", optional = true }
num-iter = "0.1.37"
bitflags = "1.0"

[dev-dependencies]
getopts = "0.2.18"
term = "0.5"
glob = "0.2.11"

[dev-dependencies.glium]
version = "0.22"
features = ["glutin"]
default-features = false

[features]
png-encoding = ["deflate"]
default = ["png-encoding"]
unstable = []
